window.labGroups = [
  {name:'基础动画与节奏', subtitle:'从一个属性，到一组精确编排的动作', indices:[0,7,8,9,1,17,18,19,20]},
  {name:'滚动与输入交互', subtitle:'滚动、拖拽、手势和指针都能成为动画的控制器', indices:[2,12,13,6,14,22]},
  {name:'文字、矢量与画布', subtitle:'拆开文字，重塑轮廓，让图形沿路径运行', indices:[3,10,26,4,11,25]},
  {name:'布局与页面适配', subtitle:'让动画在布局变化与组件切换时仍然可靠', indices:[5,23,24]},
  {name:'物理运动与数值工具', subtitle:'用速度、重力与数据映射描述运动', indices:[15,16,21]}
];
window.renderCapabilityCatalog = function(demos) {
  const overview=document.querySelector('#overview');
  overview.innerHTML='<div class="catalog-note"><strong>先看效果，再看原理。</strong><span>按技能仓库当前目录梳理；每张卡片都能进入真实实验。API 的所有参数不逐个复制。</span></div>'+window.labGroups.map((group,i)=>`<section class="catalog-group"><div class="group-heading"><div><span class="eyebrow">0${i+1} / CAPABILITIES</span><h2>${group.name}</h2><p>${group.subtitle}</p></div><span class="group-count">${group.indices.length} 个实验</span></div><div class="capability-grid">${group.indices.map(index=>{const demo=demos[index];return `<button class="capability-card" data-open-demo="${index}"><span class="card-top"><span>${String(index+1).padStart(2,'0')}</span><span class="live-badge">可操作演示 ↗</span></span><strong>${demo.name}</strong><span class="card-engine">${demo.engine}</span><span class="card-use">${demo.use}</span></button>`;}).join('')}</div></section>`).join('')+'<div class="catalog-tail"><strong>还有框架接入、性能与开发工具。</strong><span>这些能力解决“怎样写得正确”，并不都对应一种新的视觉特效。</span><button data-open-guides>查看 8 类技能与接入说明 →</button></div>';
  const skills=[
    {id:'gsap-core',title:'核心动画',status:'已有交互实验',body:'控制位置、缩放、旋转、透明度、颜色、CSS 变量以及普通对象数值；提供响应式与减少动态效果处理。',items:'to / from / fromTo / set；duration / delay / ease / stagger；repeat / yoyo；overwrite / immediateRender；函数值 / 相对值 / defaults；autoAlpha / clearProps / svgOrigin；matchMedia。',links:[7,8,1,23,25]},
    {id:'gsap-timeline',title:'时间线编排',status:'已有交互实验',body:'安排动作顺序和重叠、嵌套多个片段，用标签定位，再统一播放、暂停、倒放或调速。',items:'位置参数 < / > / +=；labels；嵌套时间线；play / pause / reverse / restart；seek / progress / timeScale；keyframes。',links:[0,9]},
    {id:'gsap-scrolltrigger',title:'滚动触发与联动',status:'已有交互实验 + 扩展说明',body:'在到达某个位置时触发动画，或用滚动进度驱动时间线；可以固定区块、吸附到关键位置、批量触发与模拟横向滚动。',items:'trigger / start / end；scrub / pin / snap；toggleActions / callbacks；batch；refresh / kill；containerAnimation；scrollerProxy 用于外部滚动系统适配。',links:[2,12,13]},
    {id:'gsap-plugins',title:'插件能力',status:'效果演示 + 开发工具说明',body:'文本、SVG、滚动、拖拽、手势、物理与自定义缓动。先导入再注册，按每个插件的规则使用和清理。',items:'ScrollTo / ScrollSmoother / Flip / Draggable / Inertia / Observer / SplitText / ScrambleText / DrawSVG / MorphSVG / MotionPath / CustomEase / CustomWiggle / CustomBounce / EasePack / Physics2D / PhysicsProps；工具与外部渲染器见下方。',links:[10,11,14,15]},
    {id:'gsap-utils',title:'数值与集合工具',status:'已有交互实验 + 完整函数索引',body:'将输入范围转换为动画参数，做吸附、随机、颜色插值和网格分布；也能处理单位、数组和作用域选择器。',items:'clamp / mapRange / normalize / interpolate / random / snap / shuffle / distribute / getUnit / unitize / splitColor / selector / toArray / pipe / wrap / wrapYoyo。shuffle 会原地打乱数组，需要保留原数组时先复制。',links:[21,8]},
    {id:'gsap-react',title:'React / Next.js 接入',status:'接入代码说明 · 本页未运行 React',body:'用 useGSAP 把动画放到组件生命周期中，限制选择器作用域，并处理更新与卸载。Next.js 的动画初始化放在客户端。',items:'useGSAP / refs / scope / dependencies / revertOnUpdate / contextSafe / SSR。contextSafe 将后创建的 GSAP 对象纳入清理；原生事件监听器仍需自己移除。',code:'// React 组件内部；需安装 @gsap/react\nconst container = useRef(null);\nuseGSAP(() => {\n  gsap.from(".item", {y:30, opacity:0});\n}, {scope:container, dependencies:[value],\n    revertOnUpdate:true});\n// 返回 <div ref={container}>…</div>\n// 使用前在模块中注册 useGSAP。',links:[24]},
    {id:'gsap-frameworks',title:'Vue / Svelte / Nuxt 接入',status:'接入代码说明 · 本页未运行框架',body:'等 DOM 挂载后创建动画，离开组件时回退；Nuxt 等服务端渲染项目应只在客户端初始化，冷门插件可按需加载。',items:'Vue onMounted / onUnmounted；Svelte onMount 返回清理函数；Nuxt client-only 初始化与插件动态导入；gsap.context 的容器作用域。',code:'// Vue：容器已定义为 ref\nlet ctx;\nonMounted(() => {\n ctx = gsap.context(() => {\n  gsap.to(".item", {x:40});\n }, container.value);\n});\nonUnmounted(() => ctx?.revert());\n\n// Svelte：组件 DOM 挂载后\nonMount(() => {\n const ctx = gsap.context(animate, container);\n return () => ctx.revert();\n});',links:[24]},
    {id:'gsap-performance',title:'性能与资源管理',status:'实现方式演示 · 不作性能跑分',body:'优先用 transform 移动元素，减少交替读写布局；高频更新复用补间；停止无用动画，控制同时运行的元素数。',items:'transform / opacity；适量 will-change；先读后写；批量与错峰；quickTo；清理上下文；布局变化后再 refresh；实际帧率仍由设备与页面复杂度决定。',links:[22,24,8]}
  ];
  const external=[
    ['MotionPathHelper','开发工具','交互编辑路径、调整控制点并导出路径数据。适合制作阶段，已有沿路径运动实验展示最终结果。','https://gsap.com/docs/v3/Plugins/MotionPathHelper/'],
    ['GSDevTools','开发工具','动画调试面板，可拖动时间、检查片段。本页提供自己的播放控件，不把它冒充为 GSDevTools。','https://gsap.com/docs/v3/Plugins/GSDevTools/'],
    ['PixiPlugin','外部引擎接入','将 GSAP 接入 PixiJS 的显示对象。需要额外安装和初始化 PixiJS；本页 Canvas 实验不调用 PixiPlugin。','https://gsap.com/docs/v3/Plugins/PixiPlugin/'],
    ['EaselPlugin','外部引擎接入','操作 EaselJS / CreateJS 对象和相关属性。出现在框架技能的插件加载清单中，本页未加载该外部引擎。','https://gsap.com/docs/v3/Plugins/EaselPlugin/'],
    ['CSSRulePlugin','兼容与样式接入','操作样式表规则，包括伪元素相关场景。出现在框架插件清单中；本页优先演示更直接的 CSS 变量动画。','https://gsap.com/docs/v3/Plugins/CSSRulePlugin/'],
    ['Webflow Interactions','产品集成背景','技能说明提到 Webflow 的交互系统使用 GSAP。它是 GSAP 在另一产品中的应用，不代表安装技能就能远程操控 Webflow。','https://gsap.com/resources/Webflow/']
  ];
  const guides=document.querySelector('#guides');
  guides.innerHTML='<div class="catalog-note"><strong>8 类技能全部列出。</strong><span>技能是给 AI 的指导文件。下方明确区分本页运行的示例、框架代码说明和外部工具。</span></div><div class="skill-grid">'+skills.map((skill,i)=>`<article class="skill-card"><span class="eyebrow">SKILL 0${i+1} / ${skill.id}</span><h2>${skill.title}</h2><span class="reference-badge">${skill.status}</span><p>${skill.body}</p><details><summary>展开能力与 API 清单</summary><p>${skill.items}</p>${skill.code?'<pre><code></code></pre>':''}</details><div class="guide-links">${skill.links.map(index=>`<button data-open-demo="${index}">${demos[index].name} ↗</button>`).join('')}</div><a class="text-link" href="https://github.com/greensock/gsap-skills/blob/main/skills/${skill.id}/SKILL.md" target="_blank" rel="noreferrer">官方技能文件 ↗</a></article>`).join('')+'</div><section class="external-section"><p class="eyebrow">TOOLS & INTEGRATIONS</p><h2>开发工具与外部接入</h2><p>以下六项提供用途与官方入口，本页没有将它们包装成可运行演示。</p><div class="external-grid">'+external.map(([name,type,body,url])=>`<article><span class="reference-badge">${type} · 说明</span><h3>${name}</h3><p>${body}</p><a class="text-link" target="_blank" rel="noreferrer" href="${url}">查看官方资料 ↗</a></article>`).join('')+'</div></section><p class="coverage-note">范围：以研究时固定版本的 gsap-skills 八份技能文件为基础，按能力类别完整列出。27 个实验是代表性实现，不表示已逐项运行所有 API、插件配置、框架或组合场景。</p>';
  guides.querySelectorAll('.skill-card').forEach((el,i)=>{if(skills[i].code)el.querySelector('code').textContent=skills[i].code;});
};
