window.createExtraDemos = function ({ stage, $, reduced, setCleanup }) {
  gsap.registerPlugin(ScrollToPlugin, ScrambleTextPlugin, MorphSVGPlugin, Observer, Physics2DPlugin, PhysicsPropsPlugin, CustomEase, CustomWiggle, CustomBounce, SlowMo, RoughEase, ExpoScaleEase, TextPlugin);
  const simple = (label, content) => { stage.innerHTML = `<span class="stage-label">${label}</span>${content}`; };
  const tl = () => gsap.timeline({ paused: true });
  const button = (id, label, fn) => {
    const el = document.createElement('button'); el.id = id; el.textContent = label; el.onclick = fn;
    $('#special-controls').append(el); return el;
  };
  const box = (extra = '') => `<div class="single-scene"><div class="demo-box" ${extra}>g.</div></div>`;
  const easeDemo = (kind) => {
    simple('DESIGN THE FEEL', '<div class="ease-display"><svg viewBox="0 0 240 160" aria-label="缓动曲线" role="img"><path d="M15 10V145H225" fill="none" stroke="#bbc5ac"/><path id="ease-curve" fill="none" stroke="#799d45" stroke-width="3"/></svg><div class="ease-lane"><div class="ease-dot"></div></div></div>');
    let ease;
    if (kind === 'custom') ease = CustomEase.create('labCustom', '.15,.85,.3,1');
    if (kind === 'wiggle') ease = CustomWiggle.create('labWiggle', { wiggles: 7, type: 'easeOut' });
    if (kind === 'bounce') ease = CustomBounce.create('labBounce', { strength: .75 });
    const points = Array.from({ length: 161 }, (_, i) => `${i ? 'L' : 'M'}${15 + i / 160 * 210},${145 - ease(i / 160) * 130}`).join(' ');
    $('#ease-curve').setAttribute('d', points);
    return tl().to('.ease-dot', kind === 'wiggle'
      ? { x: 80, duration: 3, ease }
      : { y: 145, duration: 3, ease });
  };
  return [
    { name:'属性与 3D 变换', engine:'CSSPlugin · Core', skill:'gsap-core', description:'位置、旋转、缩放、透明度、颜色与 CSS 变量一起变化。这里的立体转动作用于普通网页元素，不需要 3D 模型。', use:'卡片翻转、主题变化、状态反馈', note:'使用 x、y、rotationY 等属性；CSSPlugin 随核心提供。from / to / fromTo 决定起点与终点。', hint:'拖动进度，查看颜色、圆角和 3D 角度怎样同时变化。', code:'gsap.to(box, { rotationY: 180,\n  scale: 1.3, borderRadius: "50%",\n  backgroundColor: "#b7a3ed",\n  "--accent": "#354125", duration: 2 });',
      build(){ simple('MORE THAN MOVEMENT',box('style="--accent:#26331b"')); return tl().to('.demo-box',{rotationY:180,rotationZ:30,scale:1.35,borderRadius:'50%',backgroundColor:'#b7a3ed','--accent':'#6a4577',duration:2}).to('.demo-box',{rotationY:360,rotationZ:0,scale:1,borderRadius:'15%',backgroundColor:'#c1f75a',duration:1.5}); } },
    { name:'网格错峰波浪', engine:'Stagger · distribute', skill:'gsap-core', description:'同一组动作从中心传向四周。GSAP 根据元素在网格中的位置，自动计算每个元素开始的时刻。', use:'列表入场、点阵波浪、批量元素动画', note:'用 stagger 的 grid、from 和 amount 配置分布，避免逐个写延迟。', hint:'从中心扩散的时差由 stagger 自动计算；试试慢放。', code:'gsap.from(cells, { scale: 0.1,\n  stagger: { grid: [5,9],\n    from: "center", amount: 1 },\n  repeat: 1, yoyo: true });',
      build(){ simple('ONE ACTION / 45 ELEMENTS','<div class="wave-grid">'+Array.from({length:45},()=>'<div class="wave-cell"></div>').join('')+'</div>'); return tl().from('.wave-cell',{scale:.12,opacity:.2,rotation:90,duration:.8,stagger:{grid:[5,9],from:'center',amount:1},repeat:1,yoyo:true}); } },
    { name:'关键帧与循环', engine:'Keyframes · repeat · yoyo', skill:'gsap-timeline', description:'方块沿多个关键位置运动，再原路返回。时间线可以嵌套、加标签，像章节一样跳到指定片段。', use:'加载反馈、循环动效、分段演示', note:'repeat 指定额外重复次数，yoyo 在重复时反向；标签用于定位章节。', hint:'本例循环次数有限。点击“跳到返回”，直接从时间线标签开始。', code:'const child = gsap.to(box, {\n  keyframes: [{x:90}, {y:65}, {x:0}, {y:0}],\n  duration: 3, repeat: 1, yoyo: true\n});\nmaster.add(child).addLabel("return", 3);',
      build(){ simple('KEYFRAMES / REPEAT / YOYO',box()); const master=tl(); master.to('.demo-box',{keyframes:[{x:85},{y:65},{x:-60},{y:0,x:0}],duration:3,repeat:1,yoyo:true,ease:'none'}).addLabel('return',3); button('jump-label','跳到返回',()=>master.play('return')); return master; } },
    { name:'乱码文字揭示', engine:'ScrambleText', skill:'gsap-plugins', description:'字母先不断打乱，再逐步还原成完整标题。这种解码感来自插件逐步替换字符。', use:'科技风标题、数字揭示、状态切换', note:'使用 ScrambleText 的 text、chars 和 revealDelay 控制字符池与揭示时机。', hint:'播放时看文字从随机字符变成 MAKE IT MOVE。', code:'gsap.to(title, { duration: 3,\n  scrambleText: { text: "MAKE IT MOVE",\n    chars: "01ABCXYZ", revealDelay: .4 }\n});',
      build(){ simple('DECODE THE MESSAGE','<div class="text-demo"><div id="scramble" class="scramble-text" aria-hidden="true">•••• •• ••••</div><span class="sr-only">MAKE IT MOVE</span></div>'); return tl().to('#scramble',{duration:3,scrambleText:{text:'MAKE IT MOVE',chars:'01ABCXYZ',revealDelay:.4}}); } },
    { name:'SVG 形状变形', engine:'MorphSVG', skill:'gsap-plugins', description:'圆形连续变成多角星，再变成方形。插件会处理不同形状的路径点，让轮廓平滑过渡。', use:'图标变化、品牌图形、矢量形状动画', note:'MorphSVG 操作 SVG 路径；不同点数也可以匹配，复杂形状需检查中间状态。', hint:'把进度停在 25% 或 75%，观察轮廓之间的中间形态。', code:'tl.to(shape, { morphSVG: starPath,\n  duration: 1.8 });\ntl.to(shape, { morphSVG: squarePath,\n  duration: 1.8 });',
      build(){ simple('ONE PATH / THREE SHAPES','<svg class="morph-svg" viewBox="0 0 300 240" role="img" aria-label="圆形变为星形与方形"><path id="morph-shape" d="M220 120a70 70 0 1 1-140 0a70 70 0 1 1 140 0" fill="#b7a3ed" stroke="#32442a" stroke-width="2"/></svg>'); return tl().to('#morph-shape',{morphSVG:'M150 30L173 86L235 90L187 131L200 193L150 160L100 193L113 131L65 90L127 86Z',duration:1.8,ease:'power2.inOut'}).to('#morph-shape',{morphSVG:'M80 50H220V190H80Z',duration:1.8,ease:'power2.inOut'}); } },
    { name:'滚动到指定位置', engine:'ScrollToPlugin', skill:'gsap-plugins', description:'点击章节按钮，视口平滑滚到对应内容。动画直接控制真实滚动位置，也允许你用滚轮接管。', use:'页面目录、返回顶部、定位表单错误', note:'ScrollTo 控制滚动位置，ScrollTrigger 用滚动控制动画，两者方向不同。', hint:'点 A、B、C 跳到不同章节，也可以手动滚动。', code:'gsap.to(viewport, {\n  scrollTo: { y: section, autoKill: true },\n  duration: 1, ease: "power2.inOut"\n});',
      build(){ simple('GO TO A CHAPTER','<div id="jump-viewport" class="jump-viewport" tabindex="0" aria-label="可滚动的三个章节">'+['A','B','C'].map((s,i)=>`<div class="jump-section" id="chapter-${s}" style="background:${['#d4ecb3','#d9cff3','#ece5b9'][i]}"><span>${s}</span><p>章节 ${s} · 滚动定位</p></div>`).join('')+'</div>'); const viewport=$('#jump-viewport'); ['A','B','C'].forEach(s=>button('go-'+s,'到章节 '+s,()=>gsap.to(viewport,{scrollTo:{y:$('#chapter-'+s),autoKill:true},duration:reduced.matches?0:1,ease:'power2.inOut',overwrite:true}))); return null; } },
    { name:'平滑滚动与视差', engine:'ScrollSmoother', skill:'gsap-plugins', description:'滚动后，内容带着柔和的延迟追上来；三个方块以不同速度移动。此实验使用独立小页面中的真实 ScrollSmoother。', use:'长页面阅读、品牌叙事、分层视差', note:'ScrollSmoother 基于页面原生滚动；用 data-speed 和 data-lag 设置不同速度与滞后。', hint:'在框里滚动，或使用框内的“向下”按钮。主页面滚动保持正常。', code:'ScrollSmoother.create({\n  wrapper: "#smooth-wrapper",\n  content: "#smooth-content",\n  smooth: 1, effects: true\n});',
      build(){ stage.innerHTML='<iframe class="smooth-frame" src="smooth.html" title="ScrollSmoother 平滑滚动与视差实验"></iframe>'; return null; } },
    { name:'手势与方向识别', engine:'Observer', skill:'gsap-plugins', description:'在框里滑动或滚动，界面识别方向并切换内容。Observer 把鼠标、触控和滚轮输入归一化。', use:'滑屏切换、手势翻页、交互导航', note:'只在需要的区域监听输入，退出时移除 Observer。页面其余区域可以正常滚动。', hint:'在预览框左右拖动或滚轮滚动，也可用按钮和键盘左右键切换。', code:'Observer.create({ target: area,\n  type: "wheel,touch,pointer",\n  onLeft: next, onRight: previous,\n  onDown: next, tolerance: 25\n});',
      build(){ simple('SWIPE IN ANY DIRECTION','<div class="gesture-area" tabindex="0" role="region" aria-label="手势切换，左右方向键也可操作"><span id="gesture-count">01 / 03</span><div class="gesture-card">移动</div><p>左右滑动，探索下一张</p></div>'); let index=0; const area=$('.gesture-area'), card=$('.gesture-card'), words=['移动','感知','回应']; let tween;
        const change=delta=>{index=gsap.utils.wrap(0,3,index+delta);card.textContent=words[index];$('#gesture-count').textContent='0'+(index+1)+' / 03';tween?.kill();tween=gsap.fromTo(card,{x:delta*45,opacity:.3},{x:0,opacity:1,duration:reduced.matches?0:.4});};
        const observer=Observer.create({target:area,type:'wheel,touch,pointer',tolerance:25,preventDefault:true,onLeft:()=>change(1),onRight:()=>change(-1),onDown:()=>change(1),onUp:()=>change(-1)});
        area.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();change(e.key==='ArrowRight'?1:-1);}};
        button('gesture-prev','← 上一张',()=>change(-1));button('gesture-next','下一张 →',()=>change(1));setCleanup(()=>{observer.kill();tween?.kill();});return null; } },
    { name:'抛射与重力', engine:'Physics2D', skill:'gsap-plugins', description:'一组粒子以不同角度向上发射，再在重力作用下落下。轨迹由初始速度、角度和重力计算。', use:'庆祝粒子、抛物线、轻量物理效果', note:'Physics2D 是运动属性计算，不提供完整刚体碰撞或游戏物理世界。', hint:'本例根据可用空间缩放初速度与重力。慢放可以看清不同发射角度。', code:'gsap.to(particle, { duration: 1.6,\n  physics2D: { velocity: 240,\n    angle: -70, gravity: 300 }\n});',
      build(){ simple('VELOCITY + ANGLE + GRAVITY','<div class="physics-field">'+Array.from({length:14},(_,i)=>`<div class="particle" style="background:${i%2?'#b7a3ed':'#91bd4f'}"></div>`).join('')+'</div>'); const scale=Math.min(1,stage.clientWidth/550);return tl().to('.particle',{duration:1.6,physics2D:{velocity:i=>(210+i*5)*scale,angle:i=>-125+i*5,gravity:310*scale},ease:'none'},0); } },
    { name:'速度、加速度与阻力', engine:'PhysicsProps', skill:'gsap-plugins', description:'三条轨道分别展示固定速度、持续加速和逐渐减速。物理参数可以作用于位置等普通数值属性。', use:'滑行、减速反馈、数值驱动运动', note:'PhysicsProps 根据速度与加速度积分；friction 影响衰减，不是碰撞模拟。', hint:'三条轨道使用不同运动规则；重播比较它们前半程与后半程的速度。', code:'gsap.to(box, { duration: 2,\n  physicsProps: { x: {\n    velocity: 160, friction: .05\n  }}\n});',
      build(){ simple('THREE MOTION RULES','<div class="races physics-races">'+['匀速','加速','阻力'].map(label=>`<div class="race"><span>${label}</span><div class="track"><div class="racer"></div></div></div>`).join('')+'</div>');const distance=$('.track').clientWidth-30,t=tl();const rules=[{velocity:distance/2},{velocity:0,acceleration:distance/2},{velocity:distance*2,friction:.06}];stage.querySelectorAll('.racer').forEach((el,i)=>t.to(el,{duration:2,physicsProps:{x:rules[i]}},0));return t; } },
    { name:'自定义缓动曲线', engine:'CustomEase', skill:'gsap-plugins', description:'用一条自己定义的曲线决定速度。曲线横轴是时间，纵轴是进度；陡峭的地方运动更快。', use:'品牌专属动效、精细调整节奏', note:'CustomEase 可接收贝塞尔控制点或 SVG 路径。本例直接由同一缓动函数绘制曲线并驱动圆点。', hint:'左边是实际使用的曲线，右边是该曲线驱动的运动。',code:'const ease = CustomEase.create(\n "custom", ".15,.85,.3,1"\n);\ngsap.to(dot, { y:145, duration:3, ease });',build(){return easeDemo('custom');} },
    { name:'自定义摇摆', engine:'CustomWiggle', skill:'gsap-plugins', description:'圆点左右摇摆，幅度逐渐减小。摇摆次数和衰减方式可以单独配置。',use:'错误提示、轻微抖动、摆动反馈',note:'CustomWiggle 依赖 CustomEase；用 wiggles 与 type 决定次数和幅度变化。',hint:'曲线会跨过起点，圆点也在起点两侧摇摆，最后回到中心。',code:'const ease = CustomWiggle.create(\n "wiggle", { wiggles:7, type:"easeOut" }\n);\ngsap.to(dot, { x:80, duration:3, ease });',build(){return easeDemo('wiggle');} },
    { name:'自定义弹跳', engine:'CustomBounce', skill:'gsap-plugins', description:'控制落地后的弹跳强度。自定义弹跳比固定的 bounce.out 提供更多调节空间，还能生成挤压缓动。',use:'有重量感的落地、柔软物体反馈',note:'CustomBounce 依赖 CustomEase，strength 调整反弹力度；squash 可生成配套挤压曲线。',hint:'本例展示强度为 0.75 的弹跳；左边是实际生成的轨迹曲线。',code:'const ease = CustomBounce.create(\n "bounce", { strength:.75 }\n);\ngsap.to(dot, { y:145, duration:3, ease });',build(){return easeDemo('bounce');} },
    { name:'特殊缓动集合', engine:'EasePack', skill:'gsap-plugins', description:'SlowMo 在中间放慢，RoughEase 加入不规则变化，ExpoScaleEase 为缩放比例设计节奏。',use:'慢镜头感、不规则运动、比例缩放',note:'EasePack 包含 SlowMo、RoughEase、ExpoScaleEase。它们改变插值进度，不是视频后期滤镜。',hint:'前两行比较移动节奏；第三行展示从小到大的指数缩放。',code:'SlowMo.config(.5,.7,false)\nRoughEase.ease.config({points:20})\nExpoScaleEase.config(.5,2)',
      build(){ simple('SLOW / ROUGH / EXPONENTIAL','<div class="races physics-races">'+['SlowMo','RoughEase','ExpoScale'].map(label=>`<div class="race"><span>${label}</span><div class="track"><div class="racer"></div></div></div>`).join('')+'</div>');const nodes=stage.querySelectorAll('.racer'),distance=$('.track').clientWidth-40;return tl().to(nodes[0],{x:distance,duration:3,ease:SlowMo.config(.5,.7,false)},0).to(nodes[1],{x:distance,duration:3,ease:RoughEase.ease.config({strength:1,points:20,randomize:false,clamp:true})},0).fromTo(nodes[2],{scale:.5},{scale:2,duration:3,ease:ExpoScaleEase.config(.5,2)},0); } },
    { name:'映射、吸附与工具函数', engine:'gsap.utils', skill:'gsap-utils', description:'同一个输入同时变成角度、颜色与吸附位置。把连续数值映射到实际视觉效果，是交互动画的基础。',use:'网格吸附、进度映射、随机布局、颜色插值',note:'工具覆盖 clamp / mapRange / normalize / interpolate / snap / random / shuffle / distribute / wrap / wrapYoyo / pipe / unitize / getUnit / splitColor / selector / toArray。',hint:'拖动“输入数值”，观察连续旋转与每 20 一格的吸附结果。',code:'const p = gsap.utils.normalize(0,100,value);\nconst angle = gsap.utils.mapRange(0,1,0,360,p);\nconst snapped = gsap.utils.snap(20,value);\nconst color = gsap.utils.interpolate(\n "#c1f75a", "#b7a3ed", p);',
      build(){simple('ONE INPUT / MANY OUTPUTS','<div class="utils-scene"><div class="utility-shape">↗</div><div class="utility-readout"><span id="value-normal">进度 0.50</span><span id="value-angle">角度 180°</span><span id="value-snap">吸附 60</span></div></div>');$('#special-controls').innerHTML='<label class="wide-control">输入数值 <input id="utils-input" type="range" min="0" max="100" value="50"></label>';const update=()=>{const value=Number($('#utils-input').value),p=gsap.utils.normalize(0,100,value),angle=gsap.utils.mapRange(0,1,0,360,p);gsap.set('.utility-shape',{rotation:angle,backgroundColor:gsap.utils.interpolate('#c1f75a','#b7a3ed',p)});$('#value-normal').textContent='进度 '+p.toFixed(2);$('#value-angle').textContent='角度 '+Math.round(angle)+'°';$('#value-snap').textContent='吸附 '+gsap.utils.snap(20,value);};$('#utils-input').oninput=update;button('utils-random','随机输入',()=>{$('#utils-input').value=gsap.utils.random(0,100,1);update();});update();return null;} },
    { name:'高频鼠标跟随', engine:'quickTo · quickSetter', skill:'gsap-performance', description:'小环立即跟到指针，实心圆柔和地追上来。连续移动时复用更新器，避免每次输入都创建新动画。',use:'鼠标跟随、拖动反馈、视差倾斜',note:'quickSetter 直接写属性；quickTo 复用补间实例。此实验展示实现方式，不宣称设备帧率提升。',hint:'在框内移动鼠标或按住触屏拖动；“换个位置”也能触发跟随。',code:'const xTo = gsap.quickTo(dot,"x",{duration:.45});\nconst yTo = gsap.quickTo(dot,"y",{duration:.45});\narea.onpointermove = e => { xTo(x); yTo(y); };',
      build(){simple('IMMEDIATE VS SMOOTH','<div class="follow-area"><div class="follow-dot"></div><div class="follow-ring"></div><p>移动指针，看看它们如何跟上</p></div>');const area=$('.follow-area'),dot=$('.follow-dot'),ring=$('.follow-ring');gsap.set([dot,ring],{x:stage.clientWidth/2,y:155});const xTo=gsap.quickTo(dot,'x',{duration:reduced.matches?0:.45}),yTo=gsap.quickTo(dot,'y',{duration:reduced.matches?0:.45}),setX=gsap.quickSetter(ring,'x','px'),setY=gsap.quickSetter(ring,'y','px');const move=(x,y)=>{xTo(x);yTo(y);setX(x);setY(y);};area.onpointermove=e=>{const r=area.getBoundingClientRect();move(gsap.utils.clamp(24,r.width-24,e.clientX-r.left),gsap.utils.clamp(24,r.height-24,e.clientY-r.top));};button('follow-move','换个位置',()=>move(gsap.utils.random(40,stage.clientWidth-40),gsap.utils.random(65,230)));setCleanup(()=>{xTo.tween.kill();yTo.tween.kill();});return null;} },
    { name:'响应式与减少动态效果', engine:'matchMedia', skill:'gsap-core',description:'动画可以随屏幕大小和用户偏好变化。宽屏横向排列，窄屏纵向排列；系统要求减少动态效果时展示静态结果。',use:'手机与桌面适配、无障碍动画',note:'matchMedia 按媒体条件创建动画，条件改变时自动回退。这里读取真实视口，不是伪造媒体查询。',hint:'调整窗口宽度可切换规则；按钮可再次播放当前规则对应的动画。',code:'mm.add({ wide:"(min-width:700px)",\n reduce:"(prefers-reduced-motion:reduce)"\n}, ctx => { /* 按条件创建动画 */ });\n// 离开时 mm.revert()',
      build(){simple('A DIFFERENT SCREEN / A DIFFERENT MOTION','<div class="responsive-scene"><p id="media-status"></p><div class="responsive-dots"><i></i><i></i><i></i></div></div>');const mm=gsap.matchMedia();let animation;mm.add({wide:'(min-width:700px)',narrow:'(max-width:699px)',reduce:'(prefers-reduced-motion:reduce)'},ctx=>{const {wide,reduce}=ctx.conditions;$('.responsive-dots').style.flexDirection=wide?'row':'column';$('#media-status').textContent=(wide?'宽屏 · 横向入场':'窄屏 · 纵向入场')+(reduce?' / 减少动态效果':' / 动画可播放');animation=gsap.from('.responsive-dots i',{x:wide?-40:0,y:wide?0:-25,opacity:0,duration:reduce?0:.8,stagger:reduce?0:.12,paused:true});animation.progress(1);});button('media-play','播放当前规则',()=>{if(!reduced.matches)animation?.restart();});setCleanup(()=>mm.revert());return null;} },
    { name:'组件作用域与清理', engine:'context · revert',skill:'gsap-frameworks',description:'创建组件时启动动画，移除组件时释放它的动画；右边同名元素不受影响。这是各框架接入时共有的生命周期原则。',use:'页面切换、React / Vue / Svelte 组件',note:'这个示例真实运行原生 gsap.context；框架专属 API 在“技能与接入”中提供说明，未在本页运行。',hint:'点击挂载与卸载。数值显示该组件当前仍挂在 GSAP 时间线上的动画数。',code:'const ctx = gsap.context(() => {\n gsap.to(".local-box", { x:45 });\n}, component);\n// 卸载组件\nctx.revert();',
      build(){simple('CREATE / SCOPE / CLEAN UP','<div class="lifecycle"><div><span>当前组件</span><div id="component-slot"></div></div><div><span>外部同名元素</span><div class="local-box">外部</div></div><p id="live-count">组件动画数：0</p></div>');let local,anim;const unmount=()=>{local?.revert();local=null;$('#component-slot').innerHTML='';$('#live-count').textContent='组件动画数：'+(anim?.parent?1:0);};button('mount','挂载并播放',()=>{unmount();$('#component-slot').innerHTML='<div class="local-box">组件</div>';local=gsap.context(()=>{anim=gsap.to('.local-box',{x:35,rotation:20,duration:reduced.matches?0:1,repeat:reduced.matches?0:3,yoyo:true});},$('#component-slot'));$('#live-count').textContent='组件动画数：'+(anim.parent?1:0);});button('unmount','卸载并清理',unmount);setCleanup(()=>local?.revert());return null;} },
    { name:'Canvas 与普通对象', engine:'Object tween · ticker',skill:'gsap-core',description:'GSAP 也能改变普通 JavaScript 对象的数值。Canvas 读取这些数值进行绘制，所以动画不局限于网页标签。',use:'画布图形、数据可视化、渲染引擎接入',note:'本例是原生 Canvas 与对象补间，不是 PixiJS。绘制回调通过 gsap.ticker 注册，离开时移除。',hint:'圆环与数字从同一对象的进度绘制。拖动时间进度，Canvas 会同步更新。',code:'const state = { progress:0 };\ngsap.ticker.add(draw);\ngsap.to(state, { progress:1, duration:3 });\n// 清理：gsap.ticker.remove(draw)',
      build(){simple('ANIMATE DATA / DRAW ANYWHERE','<canvas id="lab-canvas" width="620" height="320" aria-label="对象数值驱动的圆环进度">圆环进度动画</canvas>');const canvas=$('#lab-canvas'),ctx=canvas.getContext('2d'),state={progress:0};const draw=()=>{ctx.clearRect(0,0,620,320);ctx.lineWidth=18;ctx.strokeStyle='#d9e2cc';ctx.beginPath();ctx.arc(310,165,84,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#94bd4c';ctx.beginPath();ctx.arc(310,165,84,-Math.PI/2,-Math.PI/2+Math.PI*2*state.progress);ctx.stroke();ctx.fillStyle='#36472b';ctx.font='bold 36px Arial';ctx.textAlign='center';ctx.fillText(Math.round(state.progress*100)+'%',310,177);canvas.setAttribute('aria-label','圆环进度 '+Math.round(state.progress*100)+'%');};gsap.ticker.add(draw);setCleanup(()=>gsap.ticker.remove(draw));return tl().to(state,{progress:1,duration:3,ease:'power2.inOut',onUpdate:draw});} },
    { name:'逐字替换与打字',engine:'TextPlugin',skill:'gsap-plugins',description:'把原有文字逐步替换成新文字，形成打字和句子切换效果。与 SplitText 的字符位移动画不同，它改变的是文字内容。',use:'提示语切换、打字效果、动态状态文字',note:'TextPlugin 是 GSAP 运行包的一项文本能力，也出现在技能仓库的框架插件加载清单中。',hint:'点击播放，观察两段文字依次被输入。关键代码使用真实 TextPlugin。',code:'tl.to(text, { text:"Motion begins.",\n duration:2, ease:"none" });\ntl.to(text, { text:"Make it yours.",\n duration:2, ease:"none" });',
      build(){simple('WORDS CAN CHANGE TOO','<div class="text-demo"><div id="typed-text" class="scramble-text" aria-hidden="true"></div><span class="sr-only">Motion begins. Make it yours.</span></div>');return tl().to('#typed-text',{text:'Motion begins.',duration:2,ease:'none'}).to('#typed-text',{text:'Make it yours.',duration:2,ease:'none'},'+=.3');} }
  ];
};
