"use strict";
const REV = "bdc08bee5077462e1300431408c5237438a22d00";
const UP = `https://github.com/alchaincyf/huashu-report/blob/${REV}/`;
const src = (path, label = "查看上游依据 ↗") => `<a href="${UP}${encodeURI(path)}" target="_blank" rel="noreferrer">${label}</a>`;
const line = (x,y,w,c="#c9d2dc",h=4) => `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${c}"/>`;
const text = (x,y,s,size=12,color="#203044",weight=400) => `<text x="${x}" y="${y}" font-size="${size}" fill="${color}" font-weight="${weight}" font-family="Microsoft YaHei, sans-serif">${s}</text>`;
const svg = (body,w=300,h=300,label="报告结构示意") => `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${label}" xmlns="http://www.w3.org/2000/svg">${body}</svg>`;
const templates = [
 {name:"学术报告",task:"让别人引用你的发现",kind:"academic",path:"references/结构骨架.md",flow:["摘要：可独立引用的主要发现","研究问题、证据基础与方法","分章发现、机制与竞争解释","局限性、结论、参考文献"],rules:["方法与样本口径清楚；区别描述关系与因果解释。","说明相对已有研究的贡献，不停留在资料罗列。","Figure 编号帮助定位；长报告需要更细的层级。"],ref:"Stanford AI Index / Canaries、RAND、CSET、OECD",style:"学术白、智库冷青、工程网格"},
 {name:"咨询型横版报告",task:"支持会议中的判断与行动",kind:"deck",path:"references/结构骨架.md",flow:["结论式封面、执行摘要","图形化方法论与样本构成","主体：每页一个明确发现","行动建议与必要声明"],rules:["横版 16:9；页面大标题承担主要结论。","正文少、图表清楚；来源行保留证据口径。","一页塞不下就拆页，不靠缩字和压边距。"],ref:"BCG、Deloitte、ICONIQ、KPMG（上游参照）",style:"暗色数据奢华；简报式布局需按横版适配"},
 {name:"调查报告",task:"理解一个群体的差异",kind:"survey",path:"references/结构骨架.md",flow:["前言与方法论摘要","主要发现","双栏分析与问卷结果图","分市场 / 分群体分析、方法补充"],rules:["每图标问卷原题、调查基数与该图样本量。","标调查时间、抽样与加权方式。","从 30% 到 39% 是增加 9 个百分点，不是增加 9%。"],ref:"Reuters Digital News Report、Oxford OII、Deloitte",style:"编辑部；按受众也可用杂志专题"},
 {name:"数据研报",task:"迅速定位和核对数字",kind:"research",path:"references/结构骨架.md",flow:["时间戳、分析师信息、核心判断","Exhibit 连续编号的图表","分板块 / 分地区数据表","风险、估值相关说明与声明"],rules:["图表标题采用中性描述，方便按主题查数。","允许更高表格密度，不套咨询页的大留白。","混排长文本表与纯数字表，需要不同的对齐方式。"],ref:"Morgan Stanley、UBS、J.P. Morgan",style:"工程网格；新闻数据版适合局部数据卡片"},
 {name:"学术论文",task:"接受同行审阅与复现",kind:"paper",path:"references/论文.md",flow:["Abstract、Introduction 与贡献列表","Related Work、Data & Methods","Results、Discussion、Limitations","Conclusion、References 与必要附录"],rules:["上游采用英文与 LaTeX 流程，和普通报告分轨。","方法需达到他人可以复现的程度；逐条核对文献。","投稿格式与渠道要求应另查当期官方规则。"],ref:"arXiv measurement / field study 体裁；非现成期刊模板",style:"学术白；最终服从投稿渠道要求"},
 {name:"大众科普",task:"理解领域并获得判断方法",kind:"popular",path:"references/科普.md",flow:["具体场景打开问题","展开机制，纠正直觉解释","把证据与尺度讲明白","交付读者可使用的判断工具"],rules:["用叙事带动阅读，关键口径在附近的侧栏说明。","用竞争假说讲机制，不用好故事代替证据。","结尾交付判断工具；借鉴结构方法，不模仿作者声音。"],ref:"《思考，快与慢》、卡尔·萨根、费曼等作品的结构手法",style:"暖纸本、杂志专题、编辑部"}
];
function pageDiagram(kind){
 let b="";
 if(kind==="deck") return svg(`<rect x="5" y="42" width="290" height="163" fill="white"/>${text(23,65,"发现 / DECISION",10,"#205cce")}${text(23,91,"标题直接表达本页结论",16,"#152331",700)}${line(23,108,65)}${line(23,120,55)}${line(23,132,65)}<path d="M116 171H276" stroke="#b7c4d2"/>${[50,70,95].map((h,i)=>`<rect x="${130+i*48}" y="${171-h*.6}" width="27" height="${h*.6}" fill="${i===2?'#205cce':'#a4bcdf'}"/>`).join('')}${text(23,190,"来源 · 样本 · 单位",9)}`,300,250,"咨询型报告：16比9，一页一结论，左文右图");
 b=`<rect x="51" y="5" width="198" height="280" fill="white"/>${text(67,27,"HUASHU / 结构示意",8,"#6b7b8c")}`;
 if(kind==="academic") b+=text(67,53,"研究问题与证据",16,"#182b46",700)+text(67,78,"01  摘要 / 关键发现",10)+[0,1,2].map(i=>line(67,90+i*10,160-i*8)).join('')+text(67,138,"Figure 1. 结论式图题",10)+`<path d="M76 195L117 175L159 181L221 150" stroke="#205cce" stroke-width="3" fill="none"/>`+text(67,218,"样本 N · 方法与来源",9)+line(67,234,160)+line(67,244,145)+text(67,268,"局限性 / 替代解释",10);
 if(kind==="survey") b+=text(67,53,"一个群体的不同侧面",15,"#182b46",700)+text(67,80,"关键发现",11)+text(155,83,"N = 样本量",11,"#205cce",700)+[0,1,2,3].map(i=>line(67,96+i*10,67)+line(155,96+i*10,76)).join('')+line(68,155,138,"#205cce",12)+line(68,175,106,"#a4bcdf",12)+text(68,209,"问卷原题 / Base / N",10)+[0,1,2,3].map(i=>line(67,224+i*10,67)+line(155,224+i*10,76)).join('');
 if(kind==="research") b+=text(67,51,"行业数据速查",16,"#182b46",700)+text(67,72,"日期 · 作者 · 核心判断",9)+text(67,102,"Exhibit 1. 分行业指标",10)+`<rect x="67" y="115" width="164" height="19" fill="#183a67"/>`+text(74,129,"行业       指标 A       指标 B",9,"white")+[0,1,2,3,4,5].map(i=>line(67,143+i*15,164,"#d2dbe6",1)+text(72,154+i*15,`组 ${i+1}            —              —`,9)).join('')+text(67,256,"单位 / 数据日期 / Source",9)+text(67,272,"风险与必要声明",9);
 if(kind==="paper") b+=text(68,53,"A measurable question",13,"#182b46",700)+text(104,74,"Authors · Affiliation",8)+text(128,98,"Abstract",10,"#182b46",700)+[0,1,2].map(i=>line(77,108+i*8,143)).join('')+text(67,150,"1. Introduction",11)+[0,1,2].map(i=>line(67,160+i*8,164)).join('')+text(67,199,"2. Data & Methods",11)+text(100,226,"y = f(x) + ε",15)+line(67,242,164)+text(67,268,"References / LaTeX",9);
 if(kind==="popular") b+=text(67,55,"从一个具体问题开始",15,"#182b46",700)+text(67,82,"第一幕 · 你以为的答案",10)+[0,1,2,3].map(i=>line(67,95+i*10,100)).join('')+`<rect x="179" y="91" width="52" height="69" fill="#e2ecfa"/>`+text(185,111,"口径",10,"#205cce")+text(185,128,"侧栏",10,"#205cce")+text(67,168,"第二幕 · 拆开机制",10)+[0,1,2].map(i=>line(67,181+i*10,164-i*14)).join('')+`<rect x="67" y="220" width="164" height="46" fill="#e3eeeb"/>`+text(77,240,"第三幕 · 带走判断工具",10)+text(77,255,"下次遇到主张，先问什么？",9);
 return svg(b,300,290,templates.find(t=>t.kind===kind)?.name+"页面结构示意");
}
document.querySelector('#template-grid').innerHTML=templates.map((t,i)=>`<button type="button" class="template-card" data-template="${i}" aria-controls="template-detail" aria-pressed="${i===0}"><div class="diagram-stage">${pageDiagram(t.kind)}</div><div class="template-caption"><span class="template-name"><span class="number">0${i+1}</span>${t.name}</span><small>${t.task}</small></div></button>`).join('');
function chooseTemplate(i){const t=templates[i];document.querySelectorAll('[data-template]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.template)===i));document.querySelector('#template-detail').innerHTML=`<span class="badge empirical">${t.task}</span><h3>${t.name}</h3><div class="detail-columns"><div><strong>内容骨架</strong><ol>${t.flow.map(s=>`<li>${s}</li>`).join('')}</ol></div><div><strong>决定效果的约束</strong><ul>${t.rules.map(s=>`<li>${s}</li>`).join('')}</ul></div></div><p class="source-line"><strong>上游参照：</strong>${t.ref}<br><strong>视觉搭配建议（本研究归纳）：</strong>${t.style}<br>${src(t.path)} · ${src('SKILL.md','原型选型表 ↗')}</p>`;}
document.querySelectorAll('[data-template]').forEach(b=>b.addEventListener('click',()=>chooseTemplate(Number(b.dataset.template))));chooseTemplate(0);

document.querySelector('#evidence-metrics').innerHTML=`<div class="metrics"><div class="metric"><strong>41 份</strong><span>量化基线</span><small>原始 JSON 记录数已复算</small></div><div class="metric"><strong>34 页</strong><span>页数中位数</span><small>原始 pages 字段已复算</small></div><div class="metric"><strong>35 : 6</strong><span>竖版与横版</span><small>orientation 字段已复算</small></div><div class="metric"><strong>23 / 41</strong><span>包含 PDF 书签大纲</span><small>toc_depth &gt; 0 已复算</small></div></div><p class="source-line">复算对象是仓库中的解剖结果，未重新下载 41 份 PDF 做独立测量。${src('corpus/anatomy.json','原始解剖数据 ↗')}</p><div class="evidence-bars"><div><strong>书签缺失，不代表只采用一级目录</strong><div class="bar-track" role="img" aria-label="41份中18份无书签，5份一级，18份至少两级"><span style="width:43.902%"></span><i style="width:12.196%"></i></div><p>深蓝：至少两级 18 份 · 中蓝：一级 5 份<br>浅底：无书签元数据 18 份</p><p>只看有书签的 23 份，18 份至少两级，即 78.3%。</p></div><div><strong>文字颜色占比，不等于整页色块面积</strong><div class="bar-track" role="img" aria-label="示意：上游报告的文字品牌色中位占比为2.8%，并非整页颜色占比"><span style="width:2.8%"></span></div><p>上游报告：27 份有彩度强调色的样本，品牌色文字占比中位数为 2.8%。</p><p>另有近黑正文 40/41 的归类；本页未独立重做颜色分类。</p></div></div><p class="source-line">两图统计口径不同，不可互换。${src('references/实证基线.md','统计方法与局限 ↗')}</p>`;
const ruleRows=[
 ['正文以近黑为主','样本统计 → 设计选择','作者报告 40/41 的正文主色近黑','可以形成默认色彩策略；不能推出所有正文必须同一黑色。'],
 ['默认两级目录','样本统计 → 编辑选择','有书签样本中 18/23 至少两级','无书签是元数据缺失；长文档仍应按读者检索任务设计。'],
 ['图题写发现','编辑判断','从摘要与图表阅读中提炼','查数型研报是明确例外，使用中性题目更易检索。'],
 ['附录不超过正文的 10%','编辑 + 工程经验','作者针对附录膨胀给出的体量限制','属于项目经验上限，不是由 41 份统计验证的普遍规律。'],
 ['中文正文约 10 pt，行距 1.72','工程经验 → 样式默认','英文小字基线 + 中文交付反馈','这是打印报告基线，不应直接用作网页的屏幕字号。'],
 ['边距只有一个管理来源','工程经验 → 代码约束','避免浏览器 margin 与页面 padding 叠加','A4 模式与全出血模式分开配置；横版还需修改渲染尺寸。']
];
document.querySelector('#rule-examples').innerHTML=`<div class="table-wrap"><table class="rule-table"><thead><tr><th>约束</th><th>怎么来的</th><th>依据</th><th>如何理解</th></tr></thead><tbody>${ruleRows.map(r=>`<tr>${r.map(s=>`<td>${s}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="source-line">依据：${src('references/实证基线.md','实证基线')} · ${src('references/结构骨架.md','结构骨架')} · ${src('references/视觉系统.md','视觉系统')} · ${src('references/生产流水线.md','生产流水线')}</p><div class="callout"><strong>本研究判断：</strong>“样本中常见”与“适合本次任务”是两个步骤。作者做了从观察到规范的转换，其中既有可复算数据，也有主动设计取舍；理解这个转换比照抄阈值更重要。</div>`;

const visuals=[
 ['学术白','#ffffff','#172d54','#172d54','单栏窄版心 · 衬线正文','纯文字标题、编号发现与脚注','Stanford / arXiv 系','要被引用的测量与研究'],
 ['智库冷青','#ffffff','#30353a','#14505e','双栏 · 无衬线 · 细线分节','深青章首、暖棕语义对照','CSET / RAND','政策与技术分析'],
 ['编辑部','#ffffff','#232a34','#0e2050','衬线标题 + 无衬线正文 · 双栏','嵌入小图、问卷原题、章节页眉','Reuters DNR','调查与年度综述'],
 ['暗色数据奢华','#ffffff','#152331','#1670ef','深色封面与章首 · 浅色内容页','横版大结论、超大数字、少量高亮','BCG / ICONIQ deck','会议与战略表达'],
 ['暖纸本','#faf7f2','#231f20','#ad492a','衬线正文 · 单栏 · 宽留白','整段引文、短句章首、纸本阅读感','出版社品位 / Anthropic 系','有叙事线的报告'],
 ['政务简报','#ffffff','#162634','#003da6','单栏正文 + 右侧要点栏','编号事实框、术语解释、稳重蓝','OECD / 央行报告','政策与规范性说明'],
 ['杂志专题','#ffffff','#222222','#cf202f','不对称布局 · 大章节标题','跨栏图、大数字页、时间轴带','Bloomberg Businessweek 图表风','面向大众的专题传播'],
 ['工程网格','#ffffff','#1e252a','#145ccd','严格网格 · 全无衬线','规格表、基准记分卡、等宽编号','Swiss / International Style','技术基准与工程评测'],
 ['新闻数据版','#f4f4f4','#3c3c3c','#d84532','衬线标题 + 无衬线数据','灰色背景数据、转折点焦点色、末端数值','晚点小数据 / Reuters 图表','财经数据卡片与数据洞察']
];
function visualDiagram(v,i){const [name,bg,ink,c]=v;let b=`<rect x="48" y="3" width="204" height="268" fill="${bg}" stroke="#ccd5de"/>`;
 const para=(x,y,w,n=5)=>Array.from({length:n},(_,j)=>line(x,y+j*10,w-(j===n-1?16:0),"#b3b9c0",3)).join('');
 const title=(s,y=52)=>text(65,y,s,16,ink,700);
 if(i===0)b+=text(88,48,"RESEARCH NOTE",13,c,700)+text(101,70,"一个可检验的问题",10,ink)+text(67,110,"01  主要发现",11,ink,700)+para(76,128,146,6)+line(76,211,144,c,1)+text(76,232,"[1] 文献与方法说明",9,ink);
 if(i===1)b+=`<rect x="48" y="3" width="204" height="74" fill="${c}"/>`+text(65,33,"02",15,"white")+text(65,60,"政策与技术分析",16,"white",700)+para(65,100,74,6)+para(151,100,82,6)+line(65,180,142,c,14)+line(65,205,104,"#a4551f",14)+text(65,250,"同一体系中的不同证据",9,ink);
 if(i===2)b+=text(65,29,"ANNUAL REVIEW",9,c)+title("年度观察",57)+line(65,71,170,c,1)+para(65,89,77,5)+text(162,109,"N",29,c,700)+text(154,131,"样本基数",9,ink)+para(65,155,77,7)+line(155,158,76,c,10)+line(155,179,55,"#d8ad40",10)+text(151,217,"Q. 问卷原题",9,ink)+text(151,235,"Base / N",9,ink);
 if(i===3)return svg(`<rect x="7" y="42" width="286" height="161" fill="white" stroke="#ccd5de"/><rect x="7" y="42" width="286" height="48" fill="#132336"/>${text(24,74,"一个明确的战略判断",17,"white",700)}${text(24,145,"3.4×",39,c,700)}${text(26,172,"示例倍数 · 非研究数据",9,ink)}${[30,52,82].map((h,j)=>`<rect x="${174+j*34}" y="${177-h}" width="20" height="${h}" fill="${j===2?c:'#b5c7dd'}"/>`).join('')}`,300,250,name+"视觉方向示意");
 if(i===4)b+=text(69,38,"第三章",10,c)+text(69,78,"一个问题，",20,ink,700)+text(69,108,"如何改变理解？",20,ink,700)+para(69,138,159,5)+line(69,207,32,c,3)+text(69,233,"让叙事留出停顿。",13,c);
 if(i===5)b+=`<rect x="198" y="3" width="54" height="268" fill="#e8effa"/>`+title("政策简报",45)+text(65,68,"KEY FINDINGS",9,c)+para(65,92,120,7)+`<rect x="65" y="184" width="120" height="57" fill="#edf2fa"/>`+text(73,205,"Box 1",11,c,700)+text(73,227,"关键事实与定义",10,ink)+text(205,95,"要点",10,c)+para(205,113,36,5);
 if(i===6)b+=text(62,50,"07",35,c,700)+title("重新看见",82)+title("熟悉的世界",105)+para(65,127,75,5)+text(159,161,"42",42,c,700)+text(159,181,"示例数字",9,ink)+`<path d="M65 237L111 215L161 223L237 193" stroke="${c}" stroke-width="4" fill="none"/>`;
 if(i===7)b+=text(65,29,"BENCHMARK / 001",9,c)+title("技术评测记分卡",55)+line(65,73,169,ink,2)+[0,1,2,3,4,5].map(j=>line(65,94+j*24,169,"#bfc8d2",1)+text(69,109+j*24,`0${j+1}     MODEL      —      —`,10,ink)).join('')+text(65,258,"VERSION / DATE / METHOD",8,c);
 if(i===8)b+=title("变化从这里开始",47)+text(65,71,"示意序列 / 非真实数据",9,ink)+`<path d="M68 207L103 199L138 203L173 181" stroke="#969fa8" stroke-width="3" fill="none"/><path d="M173 181L205 143L229 100" stroke="${c}" stroke-width="3" fill="none"/><path d="M173 96V220" stroke="#c0c8cf" stroke-dasharray="4"/>`+text(183,94,"转折",10,c)+text(66,241,"注 / 资料来源",9,ink)+line(65,228,169,"#cbd2d8",1);
 if([0,4].includes(i)) b=b.replaceAll('font-family="Microsoft YaHei, sans-serif"','font-family="SimSun, Songti SC, Georgia, serif"');
 if([2,6,8].includes(i)) b=b.replace(/<text[^>]*font-size="(?:16|20|35)"[^>]*>/g,tag=>tag.replace('Microsoft YaHei, sans-serif','SimSun, Songti SC, Georgia, serif'));
 return svg(b,300,276,name+"视觉方向示意");}
document.querySelector('#visual-grid').innerHTML=visuals.map((v,i)=>`<article class="visual-card"><div class="visual-preview">${visualDiagram(v,i)}</div><div class="visual-text"><h3><span class="number">0${i+1}</span>${v[0]}</h3><div class="swatches" aria-label="${v[0]}示意配色">${[v[1],v[2],v[3]].map(c=>`<i style="background:${c}" title="${c}"></i>`).join('')}</div><p><strong>${v[4]}</strong></p><p>${v[5]}</p><p>适合：${v[7]}</p><p>上游参照：${v[6]}</p><p>${src('references/视觉方向库.md','方向依据 ↗')}</p></div></article>`).join('');
document.querySelector('#visual-grid').insertAdjacentHTML('afterend',`<div class="callout"><strong>组合示例：</strong>“调查报告 + 编辑部”同时决定问卷证据结构与双栏小图布局；“调查报告 + 杂志专题”保留相同口径，但用更强的标题和图表表达。组合必须服从用途，六种原型与九种方向不是 54 套已经做好的模板。</div>`);

const chartInfo=[['横条图','类别名称较长时比较大小','hbar'],['100% 堆叠条','比较各群体的构成比例','stacked_row'],['成对柱','两组数据逐项对照，可含负值','paired_bars'],['折线','比较随时间变化的路径','line_chart'],['大数字','突出单个重要数值及其口径','big_stat'],['发散堆叠条','围绕中点比较正负态度','diverging'],['斜率图','两个时点之间的水平变化','slope'],['象限散点','同时比较两个变量的位置','quadrant']];
function chartDiagram(i){let b="";const blue="#205cce",gray="#a8bddb";
 if(i===0)b=[120,90,150].map((w,j)=>line(22,15+j*26,w,j===2?blue:gray,13)).join('');
 if(i===1)b=[80,110,50].map((w,j)=>line(14,15+j*26,w,blue,13)+line(14+w,15+j*26,170-w,gray,13)).join('');
 if(i===2)b=`<path d="M15 65H190" stroke="#7c8a99"/>`+[35,-20,47].map((h,j)=>`<rect x="${25+j*54}" y="${h<0?65:65-h}" width="16" height="${Math.abs(h)}" fill="${blue}"/><rect x="${44+j*54}" y="42" width="16" height="23" fill="${gray}"/>`).join('');
 if(i===3)b=`<path d="M16 87L62 56L111 69L169 20" stroke="${blue}" stroke-width="3" fill="none"/><path d="M16 62L62 77L111 44L169 51" stroke="${gray}" stroke-width="3" fill="none"/>`+text(175,25,"A",11,blue)+text(175,55,"B",11,"#557299");
 if(i===4)b=text(43,60,"42%",44,blue,700)+text(28,88,"示例值 / 附口径与来源",11,"#53677c");
 if(i===5)b=`<path d="M99 10V93" stroke="#8c9aaa"/>`+[35,65,45].map((w,j)=>line(99-w,18+j*25,w,"#b88455",13)+line(99,18+j*25,85-w*.5,blue,13)).join('');
 if(i===6)b=`<path d="M30 12V91M169 12V91" stroke="#b7c6d6"/>`+[0,1,2].map((_,j)=>`<path d="M30 ${25+j*25}L169 ${74-j*28}" stroke="${j===1?gray:blue}" stroke-width="2"/><circle cx="30" cy="${25+j*25}" r="4" fill="${blue}"/><circle cx="169" cy="${74-j*28}" r="4" fill="${blue}"/>`).join('');
 if(i===7)b=`<path d="M15 54H185M101 10V100" stroke="#bccbd9"/>`+[[40,30,'A'],[138,25,'B'],[65,80,'C'],[148,75,'D']].map(([x,y,l])=>`<circle cx="${x}" cy="${y}" r="5" fill="${blue}"/>${text(x+9,y+4,l,11)}`).join('');
 return svg(b,210,110,chartInfo[i][0]+"示意，数值仅用于说明图型");}
document.querySelector('#chart-grid').innerHTML=chartInfo.map((c,i)=>`<article class="chart-card">${chartDiagram(i)}<h3>${c[0]}</h3><p>${c[1]}</p><code>${c[2]}()</code></article>`).join('');
document.querySelector('#chart-grid').insertAdjacentHTML('afterend',`<p class="source-line">以上为本页重绘的图型示意，示例值不用于研究结论。${src('assets/chart.py','8 个函数实现 ↗')} · ${src('references/图表模式库.md','13 条表达方法 ↗')}</p>`);

document.querySelector('#detail-examples').innerHTML=`<div class="compare-grid"><article class="compare"><h3>01 / 负值不能被画成“没有变化”</h3>${svg(`${text(15,27,'错误：把负值压成零',13,'#9b4e1f',700)}${text(247,27,'正确：在零线下绘制',13,'#205cce',700)}<path d="M23 111H197M253 111H427" stroke="#6c7c8e"/>${line(59,63,34,'#a8bddb',48)}${text(58,52,'+12',12)}${text(122,130,'−11',12,'#9b4e1f')}${line(290,63,34,'#a8bddb',48)}${line(353,111,34,'#a15a13',44)}${text(291,52,'+12',12)}${text(354,176,'−11',12,'#9b4e1f')}${text(17,111,'0',10)}${text(247,111,'0',10)}`,460,190,'同一组示例值正12与负11，错误图遗漏负柱，正确图在零线下方画负柱')}<p>成对柱函数专门计算零线位置；图形语义比装饰更重要。负值支持不能泛化到所有图型。${src('assets/chart.py','对应实现 ↗')}</p></article><article class="compare"><h3>02 / 长文本表格必须保住列边界</h3>${svg(`${text(12,27,'错误：两列粘成一句',13,'#9b4e1f',700)}${text(242,27,'正确：边界与间距明确',13,'#205cce',700)}<rect x="12" y="59" width="213" height="68" fill="#fff0de"/>${text(20,96,'84%尚未完成部署',18)}<rect x="242" y="59" width="205" height="68" fill="#edf2fa"/><path d="M309 59V127" stroke="#9db3ce"/>${text(255,96,'84%',18)}${text(321,86,'尚未完成',14)}${text(321,108,'部署',14)}`,460,155,'错误的数字与口径相接，正确表格以分隔线和间距分开两列')}<p>混排表使用固定列宽、允许长词换行，并保持列间边界。纯数字表可右对齐，不能把混排表规则扩展到所有表格。示例值为演示。${src('assets/base.css','样式依据 ↗')}</p></article></div>`;
const detailItems=[
 ['数字先有口径，再进入正文','数据层','记录 value、basis、n、src 与 verified；把“原始数字”“统计分母”“自己的判断”分开。核验状态需要有人负责，字段存在不等于已经核实。','references/生产流水线.md'],
 ['百分比与百分点分清','内容层','示例：30% → 39%，相差 9 个百分点，相对增幅为 30%。问卷结果还应标 Base、样本量、采集时间与加权方式。','references/结构骨架.md'],
 ['图题有结论，但不制造因果','编辑层','图题负责说明发现；机制分析要提出竞争解释。相关性图不能单凭箭头升级成因果机制图，研报图题则优先使用可检索的中性描述。','references/研究深度.md'],
 ['标注长度反过来决定画布','图表层','横条图按标签和数值文字估算预留宽度，大数字组件按实际文字增宽。字符宽度是估算，字体回退和极长文本仍需看实际结果。','assets/chart.py'],
 ['同一份报告只保留一套边距来源','版式层','A4 默认由渲染器控制上下左右边距；全出血页改为零打印边距和页面内边距。内容放不下时拆页，而非反复压缩留白。','references/生产流水线.md'],
 ['长表跨页，但一行不拆开','版式层','允许表格跨页，表头在后续页重复，单行保持完整；标题避免独占页尾，图表作为整体搬到下一页。超高单行仍需重新组织。','assets/base.css'],
 ['长网址可能缩小整本报告','版式层','一个不可断行的 URL 就可能撑宽文档，浏览器为了适配纸张而整体缩小。对来源、图注与正文容器设长词换行，从根源避免溢出。','assets/base.css'],
 ['双栏给两边都设最小宽度','版式层','只有一侧可伸缩、另一侧又允许任意换行时，可能出现一列被压成一个字宽。两侧明确最小宽度，装不下时整体换行。','assets/base.css'],
 ['目录页码是循环计算的结果','渲染层','先重建 HTML，再渲染并定位章节，排除目录页自身，回填页码后重新渲染。最多四轮；依赖章节正则和特定 toc_row 写法。','assets/render.py'],
 ['检查最终页面，而非只相信样式','检查层','把 PDF 渲成灰度图测边距；低内容页与大面积留白只作为候选提示。深色覆盖多的页面会跳过边距检查，需人工确认。','assets/render.py'],
 ['能由生成器判断的，不让作者背','流程层','首字下沉遇到数字和过于简单的汉字会失效：生成器判断是否启用即可。共享规则应放在统一组件中，避免分章写作时各自走样。','references/生产流水线.md'],
 ['机器查结构，阅读者查意义','检查层','脚本难以判断机制解释是否成立、色彩是否误导、图表是否被裁切。规则需要明确由代码、数据核验还是逐页观察负责，不能用一个“通过”概括所有质量。','SKILL.md']
];
document.querySelector('#detail-grid').innerHTML=detailItems.map((d,i)=>`<details${i<2?' open':''}><summary><span class="number">${String(i+3).padStart(2,'0')}</span>${d[0]}</summary><p><span class="badge engineering">${d[1]}</span></p><p>${d[2]}</p><p>${src(d[3])}</p></details>`).join('');
document.querySelector('#pipeline-content').innerHTML=`<p class="section-intro">上游的生产过程依赖 Agent 编写具体报告。仓库提供规则、图表组件和渲染器；数据表与内容生成器仍需针对任务制作。</p><div class="pipeline"><div><b>01 / 任务定义</b><h3>读者与核心发现</h3><p>明确阅读用途、报告原型、可复述的结论与外部基准。</p></div><span class="pipeline-arrow">→</span><div><b>02 / 数据约束</b><h3>数据表.json</h3><p>每项数字附口径、样本、来源与核验记录，供正文引用。</p></div><span class="pipeline-arrow">→</span><div><b>03 / 内容与视觉</b><h3>build.py + 组件</h3><p>写发现、机制与文献定位；组合共享样式和 SVG 图表。</p></div><span class="pipeline-arrow">→</span><div><b>04 / 生成与检查</b><h3>HTML → PDF</h3><p>目录回填、机械与几何检查，再逐页判断阅读效果。</p></div></div><div class="branch"><strong>论文分支：</strong>数据纪律保留 → LaTeX 正文 + 文献 + 矢量图 → 编译 PDF 与投稿源文件包。上游写到的投稿政策具有时效性，本页不将其视为已核实的现行规则。</div><div class="table-wrap"><table class="rule-table"><thead><tr><th>放在哪里</th><th>适合承担什么</th><th>还需要谁判断</th></tr></thead><tbody><tr><td>技能说明</td><td>受众选择、证据强度、机制分析、叙述节奏</td><td>研究与编辑判断</td></tr><tr><td>结构化数据</td><td>口径、分母、出处、核验状态</td><td>核验者回到原始来源</td></tr><tr><td>共享 CSS / 图表组件</td><td>字号层级、分页、边距、负值、标签位置</td><td>复杂版式的视觉确认</td></tr><tr><td>渲染与检查器</td><td>重复生成、页码定位、占位符与几何检测</td><td>处理警报、发现机器漏检</td></tr></tbody></table></div><p class="source-line">${src('references/生产流水线.md','完整制作流程 ↗')} · ${src('assets/render.py','渲染器实现 ↗')}</p><div class="boundary"><h3>规范说了什么，与代码做了什么，要分别看。</h3><ul><li><strong>图号：</strong>说明提到编号连续性；当前代码主要查 Figure / Exhibit 混用与重复，没有完整的连续编号校验。</li><li><strong>负值：</strong>成对柱显式支持负柱；横条函数直接按数值算宽度，负数可能产生无效 SVG 宽度，不能认为八种图型都支持负值。</li><li><strong>页码：</strong>回填使用正则与固定调用格式；目录自检主要检查是否提取到页码，并非全面核对所有条目。</li><li><strong>“检查通过”：</strong>警报以文本输出，发现问题不自动保证非零退出；不能直接把它当作严格发布门禁。</li><li><strong>长文档：</strong>检查器统计的是特定 &lt;em&gt; 标记，并按特定分页结构识别章节；换成其他标签或模板可能漏检。</li></ul><p class="source-line">以上为固定版本的代码阅读结论。${src('assets/chart.py','图表实现')} · ${src('assets/render.py','检查器实现')}</p></div>`;

const primarySources=[
 ['Stanford HAI · AI Index 2026','学术报告方向；可进一步研究章节导航、方法说明与图表组织。','https://hai.stanford.edu/ai-index/2026-ai-index-report'],
 ['Reuters Institute · Digital News Report 2026','调查报告方向；上游从其问卷标注、双栏和分市场结构提取方法。','https://reutersinstitute.politics.ox.ac.uk/digital-news-report/2026'],
 ['BCG · AI at Work 2026','咨询报告方向；上游参考其结论页、样本构成与对比表达。','https://www.bcg.com/publications/2026/ai-at-work-why-strategy-matters-more-than-tools'],
 ['ICONIQ · State of AI 2026','咨询报告方向；上游参考内容地图、分组标签和数据表达。','https://www.iconiq.com/growth/reports/2026-state-of-ai-bi-annual-snapshot'],
 ['CSET · When AI Builds AI','学术 / 智库方向；可进一步研究技术与政策报告如何交代证据。','https://cset.georgetown.edu/publication/when-ai-builds-ai/'],
 ['Morgan Stanley · Mapping AI’s Rate of Change','数据研报方向；上游参考 Exhibit 编号与密集数据表。','https://www.morganstanley.com/content/dam/msdotcom/en/assets/pdfs/Research_AI-Rate-of-Change.pdf']
];
document.querySelector('#source-content').innerHTML=`<p class="section-intro">本页把上游作者的总结、可复算数据和本研究解释分开。下列机构入口已于 2026-09-15 打开确认；版式技巧的对应关系主要依据上游文档，本次未逐页重做这些 PDF 的解剖。</p><h3>第一层 / 直接阅读仓库</h3><div class="sources-list">${[['SKILL.md','六类原型、工作顺序与交付检查。'],['references/实证基线.md','样本框、测量方法、统计口径与局限。'],['corpus/anatomy.json','41 份记录的原始量化结果。'],['references/视觉方向库.md','九种方向的字体、配色、布局和参照系。'],['references/图表模式库.md','13 条表达方法及选图逻辑。'],['references/生产流水线.md','工程故障、页面模式与规则分层。'],['references/科普.md','叙事结构、侧栏口径与大众判断工具。'],['references/论文.md','论文写作和 LaTeX 流程；政策另行核验。']].map(([path,desc])=>`<article class="source-card"><h3>${src(path,path.split('/').pop())}</h3><p>${desc}</p></article>`).join('')}</div><h3 style="margin-top:30px">第二层 / 回到机构报告入口</h3><div class="sources-list">${primarySources.map(([name,desc,url])=>`<article class="source-card"><h3>${name}</h3><p>${desc}</p><a href="${url}" target="_blank" rel="noreferrer">官方来源 ↗</a><p class="micro">入口已确认 · 技巧归因来自上游</p></article>`).join('')}</div><p class="source-line">更完整的机构与报告链接见 ${src('corpus/samples.md','43 份样本清单 ↗')}。科普作品与新闻数据版属于补充的结构 / 视觉参照，不都属于量化样本。</p><div class="boundary"><h3>使用这些结论时，保留四个边界。</h3><ul><li><strong>计数不同：</strong>74 是候选数，42 是初期 PDF 采集数，41 是统计记录数，43 是后来补充后的报告清单数。</li><li><strong>样本有限：</strong>重点来自特定时期、英文机构、AI 与科技主题和可获取全文的报告，不能直接代表所有行业与语言。</li><li><strong>代理测量：</strong>矢量绘图对象数不等于真实图表数；文字颜色占比不包含背景和图表填充面积。</li><li><strong>上游有修订与不一致：</strong>清单仍记录若干实际下载文件与标称报告不一致；基线文档另记修复。引用具体样本前应重新对照文件身份。视觉与结构文档的个别“统一规则”也存在场景例外。</li></ul><p class="source-line">${src('references/实证基线.md','方法与修订记录')} · ${src('corpus/samples.md','样本身份备注')}</p></div><p class="micro">研究版本：${REV}。本页复算页数、横竖版与书签指标；未生成上游完整报告，未验证其所有渲染分支。原仓库为 MIT 许可，原始机构报告各自保留许可与版权。本页只提供来源链接和独立重绘图示。</p>`;
