'use strict';
const base='https://github.com/AiuniAI/Unique3D/blob/6311af200ee197544e82e0f2557cd890edd60416/';
const steps=[
  {kind:'前处理',title:'先把主体准备好',description:'从背景中提取物体，裁切、居中并统一画幅，让后续模型看到完整且清晰的主体。',input:'单张 RGB / RGBA 图片',output:'处理后的正面参考图',noteTitle:'输入决定起点',note:'尽量正面、主体完整、遮挡少。被裁掉的最长方向可能使比例失真；模型无法从缺失的观测中确认真实背面。',source:'app/custom_models/mvimg_prediction.py'},
  {kind:'预训练扩散模型',title:'生成物体周围的四个视图',description:'经过微调的图像扩散模型根据输入图生成四个正交方向的外观。先从 256 × 256 的图像开始，建立尽量一致的物体身份。',input:'正面参考图 + 已有模型权重',output:'四个方向的 RGB 图像',noteTitle:'这里发生的是推测',note:'一张正面图可以对应很多种背面。模型借助训练中学到的物体规律补全，合理不代表真实。',source:'app/custom_models/mvimg_prediction.py'},
  {kind:'法线预测与图像增强',title:'不仅看颜色，还要知道表面朝向',description:'法线模型预测表面朝向，帮助区分凸起、凹陷与颜色变化。论文用 ControlNet 与 Real-ESRGAN 等分级增强，将多视图颜色图从 256 提升到 512，再到 2048；法线也进行增强。',input:'多视图颜色图',output:'高分辨率颜色图与法线图',noteTitle:'法线不是表面颜色',note:'法线图用 RGB 编码方向。它告诉算法哪里朝上、哪里朝侧面，是塑造鼻尖、褶皱和雕刻细节的重要线索。',source:'app/custom_models/normal_prediction.py'},
  {kind:'ISOMER 几何重建',title:'把二维线索落实成三维表面',description:'根据正背面的法线估计初始形状并拼合网格，再渲染、比较轮廓与法线、调整顶点和网格连接。ExplicitTarget 综合可见视角，减少生成视图间的冲突。',input:'多视图轮廓与法线',output:'由粗到细的三角网格',noteTitle:'优化的是这一个物体',note:'这一步调整当前网格，不是在重新训练通用大模型。参考视图互相矛盾时，重建也可能出现伪影和形状误差。',source:'mesh_reconstruction/refine.py'},
  {kind:'颜色投影与导出',title:'把形状与颜色保存为 GLB',description:'按可见性和观察方向把多视图颜色投影到网格，并补齐未观测区域。默认导出路径使用顶点颜色，将顶点和三角面保存到 GLB。',input:'细化网格 + 多视图颜色',output:'带顶点颜色的 .glb 文件',noteTitle:'资产初稿还需要整理',note:'可旋转、可编辑不等于已完成 UV、PBR 材质、骨骼动画或真实尺寸。进入游戏或打印流程前需要专项后处理。',source:'scripts/utils.py'}
];
const tabs=[...document.querySelectorAll('[data-step]')];
function showStep(index,focus=false){const s=steps[index];tabs.forEach((t,i)=>{t.setAttribute('aria-selected',String(i===index));t.tabIndex=i===index?0:-1});document.querySelector('#stage').setAttribute('aria-labelledby',`tab-${index}`);for(const [id,value] of Object.entries({'stage-kind':s.kind,'stage-title':s.title,'stage-description':s.description,'stage-input':s.input,'stage-output':s.output,'stage-note-title':s.noteTitle,'stage-note-text':s.note,'stage-symbol':String(index+1).padStart(2,'0')}))document.getElementById(id).textContent=value;document.querySelector('#stage-source').href=base+s.source;if(focus)tabs[index].focus();}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>showStep(index));tab.addEventListener('keydown',e=>{let next=index;if(e.key==='ArrowRight')next=(index+1)%tabs.length;else if(e.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();showStep(next,true);});});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});document.querySelectorAll('[data-category]').forEach(row=>row.hidden=button.dataset.filter!=='all'&&row.dataset.category!==button.dataset.filter);}));
const gallery=document.querySelector('#official-gallery');gallery.addEventListener('error',()=>{gallery.hidden=true;document.querySelector('#gallery-fallback').hidden=false;});
