const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
(async () => {
 const browser = await chromium.launch({headless:true});
 const page = await browser.newPage({viewport:{width:1440,height:1080}});
 const errors=[];
 page.on('pageerror', e=>errors.push(e.message));
 page.on('console', message=>{if(message.type()==='warning'||message.type()==='error') errors.push(message.text());});
 await page.goto('http://127.0.0.1:8099/#demo-1');
 await page.waitForFunction(()=>window.gsap && document.querySelectorAll('.shape').length===3);
 await page.locator('#progress').fill('500');
 assert.equal(await page.locator('#progress-label').textContent(),'50%');
 await page.locator('#play').click();
 await page.waitForTimeout(120);
 assert.ok(Number(await page.locator('#progress').inputValue())>500);
 await page.locator('#play').click();
 await page.locator('#reverse').click();
 await page.waitForTimeout(150);
 await page.locator('#play').click();
 assert.ok(Number(await page.locator('#progress').inputValue())<540);
 await page.locator('#progress').fill('1000');
 fs.mkdirSync(path.join(__dirname,'../assets'),{recursive:true});
 await page.screenshot({path:path.join(__dirname,'../assets/preview.png'),fullPage:true});
 for(const index of [1,3,4]){
  await page.locator(`[data-index="${index}"]`).click();
  await page.locator('#progress').fill('500');
  assert.equal(await page.locator('#progress-label').textContent(),'50%');
 }
 await page.locator('[data-index="2"]').click();
 await page.locator('#progress').fill('750');
 await page.waitForTimeout(100);
 assert.ok(Number(await page.locator('#progress').inputValue())>=740);
 assert.ok(await page.locator('.scroll-orbit').evaluate(el=>Number(gsap.getProperty(el,'rotation')))>180);
 await page.locator('#scroll-top').click();
 await page.waitForTimeout(700);
 assert.ok(await page.locator('.scroll-viewport').evaluate(el=>el.scrollTop)<5);
 await page.locator('[data-index="5"]').click();
 await page.locator('#layout').click();
 await page.waitForTimeout(1100);
 assert.ok(await page.locator('.flip-grid').evaluate(el=>el.classList.contains('list')));
 await page.locator('#shuffle').click();
 await page.waitForTimeout(1100);
 assert.equal(await page.locator('.tile').first().textContent(),'02');
 await page.locator('[data-index="6"]').click();
 const box=page.locator('.drag-object');
 await box.focus(); await page.keyboard.press('ArrowRight');
 assert.equal(await box.evaluate(el=>Number(gsap.getProperty(el,'x'))),25);
 const r=await box.boundingBox();
 await page.mouse.move(r.x+25,r.y+25);await page.mouse.down();await page.mouse.move(r.x+145,r.y+90,{steps:10});await page.mouse.up();
 await page.waitForTimeout(1500);
 assert.ok(await box.evaluate(el=>Number(gsap.getProperty(el,'x')))>25);
 await page.locator('#drag-reset').click();
 assert.equal(await box.evaluate(el=>Number(gsap.getProperty(el,'x'))),0);
 for (let i=0;i<7;i++) await page.locator(`[data-index="${i}"]`).click();
 assert.equal(await page.evaluate(()=>ScrollTrigger.getAll().length),0);
 assert.equal(await page.evaluate(()=>Draggable.get(document.querySelector('.drag-object'))!==undefined),true);
 await page.setViewportSize({width:390,height:844});
 await page.waitForTimeout(300);
 for(let i=0;i<7;i++){
  await page.locator(`[data-index="${i}"]`).click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`mobile overflow on ${i}`);
 }
 await page.locator('[data-index="0"]').click();
 await page.locator('#progress').fill('1000');
 await page.screenshot({path:path.join(__dirname,'../assets/mobile.png'),fullPage:true});
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.locator('[data-index="3"]').click();
 assert.equal(await page.locator('#progress').inputValue(),'1000');
 assert.equal(await page.locator('#play').textContent(),'▶ 播放');
 assert.deepEqual(errors,[]);
 console.log('PASS: seven demos; transport and scrub; scroll; Flip; pointer/keyboard drag; lifecycle cleanup; 390px layout; reduced motion; no browser errors.');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
